add_subdirectory(cdh)
add_subdirectory(util)
add_subdirectory(cmd)
add_subdirectory(comms)
add_subdirectory(adcs)
add_subdirectory(eps)
add_subdirectory(gps)
add_subdirectory(serial_protocol)
add_subdirectory(udp)
add_subdirectory(vendor SYSTEM)


if("DET" IN_LIST SMALLSAT_SUBSYSTEMS_LIST)
    add_subdirectory(det)
endif()
