#include "struct_decode_operators.h"

std::ostream& operator<<(std::ostream& os, CubeSpace::ADCSStateTelemetryFormat const& state){
    os << "AttitudeEstimationMode: " << (int) state.AttitudeEstimationMode << "\n";;
    os << "ControlMode: " << (int) state.ControlMode << "\n";
    os << "ADCSRunMode: " << (int) state.ADCSRunMode << "\n";
    os << "ASGP4Mode: " << (int) state.ASGP4Mode << "\n";
    os << "CubeControlSignalEnabled: " << state.CubeControlSignalEnabled << "\n";
    os << "CubeControlMotorEnabled: " << state.CubeControlMotorEnabled << "\n";
    os << "CubeSense1Enabled: " << state.CubeSense1Enabled << "\n";
    os << "CubeSense2Enabled: " << state.CubeSense2Enabled << "\n";
    os << "CubeWheel1Enabled: " << state.CubeWheel1Enabled << "\n";
    os << "CubeWheel2Enabled: " << state.CubeWheel2Enabled << "\n";
    os << "CubeWheel3Enabled: " << state.CubeWheel3Enabled << "\n";
    os << "CubeStarEnabled: " << state.CubeStarEnabled << "\n";
    os << "GPSReceiverEnabled: " << state.GPSReceiverEnabled << "\n";
    os << "GPSLNAPowerEnabled: " << state.GPSLNAPowerEnabled << "\n";
    os << "MotorDriverEnabled: " << state.MotorDriverEnabled << "\n";
    os << "SunisAboveLocalHorizon: " << state.SunisAboveLocalHorizon << "\n";
    os << "CubeSense1CommunicationsError: " << state.CubeSense1CommunicationsError << "\n";
    os << "CubeSense2CommunicationsError: " << state.CubeSense2CommunicationsError << "\n";
    os << "CubeControlSignalCommunicationsError: " << state.CubeControlSignalCommunicationsError << "\n";
    os << "CubeControlMotorCommunicationsError: " << state.CubeControlMotorCommunicationsError << "\n";
    os << "CubeWheel1CommunicationsError: " << state.CubeWheel1CommunicationsError << "\n";
    os << "CubeWheel2CommunicationsError: " << state.CubeWheel2CommunicationsError << "\n";
    os << "CubeWheel3CommunicationsError: " << state.CubeWheel3CommunicationsError << "\n";
    os << "CubeStarCommunicationsError: " << state.CubeStarCommunicationsError << "\n";
    os << "MagnetometerRangeError: " << state.MagnetometerRangeError << "\n";
    os << "Cam1SRAMOvercurrentDetected: " << state.Cam1SRAMOvercurrentDetected << "\n";
    os << "Cam13V3OvercurrentDetected: " << state.Cam13V3OvercurrentDetected << "\n";
    os << "Cam1SensorBusyError: " << state.Cam1SensorBusyError << "\n";
    os << "Cam1SensorDetectionError: " << state.Cam1SensorDetectionError << "\n";
    os << "SunSensorRangeError: " << state.SunSensorRangeError << "\n";
    os << "Cam2SRAMOvercurrentDetected: " << state.Cam2SRAMOvercurrentDetected << "\n";
    os << "Cam23V3OvercurrentDetected: " << state.Cam23V3OvercurrentDetected << "\n";
    os << "Cam2SensorBusyError: " << state.Cam2SensorBusyError << "\n";
    os << "Cam2SensorDetectionError: " << state.Cam2SensorDetectionError << "\n";
    os << "NadirSensorRangeError: " << state.NadirSensorRangeError << "\n";
    os << "RateSensorRangeError: " << state.RateSensorRangeError << "\n";
    os << "WheelSpeedRangeError: " << state.WheelSpeedRangeError << "\n";
    os << "CoarseSunSensorError: " << state.CoarseSunSensorError << "\n";
    os << "StarTrackerMatchError: " << state.StarTrackerMatchError << "\n";
    os << "StarTrackerOvercurrentDetected: " << state.StarTrackerOvercurrentDetected << "\n";
    os << "OrbitParametersareInvalid: " << state.OrbitParametersareInvalid << "\n";
    os << "ConfigurationisInvalid: " << state.ConfigurationisInvalid << "\n";
    os << "ControlModeChangeisnotallowed: " << state.ControlModeChangeisnotallowed << "\n";
    os << "EstimatorChangeisnotallowed: " << state.EstimatorChangeisnotallowed << "\n";
    os << "CurrentMagnetometerSamplingMode: " << (int) state.CurrentMagnetometerSamplingMode << "\n";
    os << "Modelledandmeasuredmagneticfielddiffersinsize: " << state.Modelledandmeasuredmagneticfielddiffersinsize << "\n";
    os << "NodeRecoveryError: " << state.NodeRecoveryError << "\n";
    os << "CubeSense1RuntimeError: " << state.CubeSense1RuntimeError << "\n";
    os << "CubeSense2RuntimeError: " << state.CubeSense2RuntimeError << "\n";
    os << "CubeControlSignalRuntimeError: " << state.CubeControlSignalRuntimeError << "\n";
    os << "CubeControlMotorRuntimeError: " << state.CubeControlMotorRuntimeError << "\n";
    os << "CubeWheel1RuntimeError: " << state.CubeWheel1RuntimeError << "\n";
    os << "CubeWheel2RuntimeError: " << state.CubeWheel2RuntimeError << "\n";
    os << "CubeWheel3RuntimeError: " << state.CubeWheel3RuntimeError << "\n";
    os << "CubeStarRuntimeError: " << state.CubeStarRuntimeError << "\n";
    os << "MagnetometerError: " << state.MagnetometerError << "\n";
    os << "RateSensorFailure: " << state.RateSensorFailure << "\n";
    os << "unused_0[0]: " << state.unused_0[0] << "\n";
    os << "unused_0[1]: " << state.unused_0[1] << "\n";
    os << "unused_0[2]: " << state.unused_0[2] << "\n";
    os << "EstimatedRollAngle: " << state.EstimatedRollAngle << "\n";
    os << "EstimatedPitchAngle: " << state.EstimatedPitchAngle << "\n";
    os << "EstimatedYawAngle: " << state.EstimatedYawAngle << "\n";
    os << "Estimatedq1: " << state.Estimatedq1 << "\n";
    os << "Estimatedq2: " << state.Estimatedq2 << "\n";
    os << "Estimatedq3: " << state.Estimatedq3 << "\n";
    os << "EstimatedXAngularRate: " << state.EstimatedXAngularRate << "\n";
    os << "EstimatedYAngularRate: " << state.EstimatedYAngularRate << "\n";
    os << "EstimatedZAngularRate: " << state.EstimatedZAngularRate << "\n";
    os << "Xposition: " << state.Xposition << "\n";
    os << "Yposition: " << state.Yposition << "\n";
    os << "Zposition: " << state.Zposition << "\n";
    os << "XVelocity: " << state.XVelocity << "\n";
    os << "YVelocity: " << state.YVelocity << "\n";
    os << "ZVelocity: " << state.ZVelocity << "\n";
    os << "Latitude: " << state.Latitude << "\n";
    os << "Longitude: " << state.Longitude << "\n";
    os << "Altitude: " << state.Altitude << "\n";
    os << "ECEFPositionX: " << state.ECEFPositionX << "\n";
    os << "ECEFPositionY: " << state.ECEFPositionY << "\n";
    os << "ECEFPositionZ: " << state.ECEFPositionZ << "";
    return os;
}

